// this file is autogenerated, don't modify it

export default [
  // user
  {
    path: '/login',
    component: './login',
  },
  // app
  {
    path: '/',
    component: '../layouts/BasicLayout',
    routes: [
      // BasicLayout 下的子路由会被转化成 menu data
      { path: '/', redirect: '/dashboard/analysis' },
      {
        path: '/test',
        name: 'test',
        icon: 'profile',
        isMenuData: true,
        routes: [
          {
            name: 'test-a',
            path: '/test/a',
            component: './test-a',
            isMenuData: true,
          },
          {
            name: 'test-b',
            path: '/test/b',
            component: './test-b',
            isMenuData: true,
          }
        ],
      },
      // {
      //   path: '/dashboard',
      //   name: 'dashboard',
      //   icon: 'dashboard',
      //   isMenuData: true,
      //   routes: [
      //     {
      //       path: '/dashboard/analysis',
      //       name: 'analysis',
      //       component: './Dashboard/Analysis',
      //       isMenuData: true,
      //     },
      //     {
      //       path: '/dashboard/monitor',
      //       name: 'monitor',
      //       component: './Dashboard/Monitor',
      //       isMenuData: true,
      //     },
      //     {
      //       path: '/dashboard/workplace',
      //       name: 'workplace',
      //       component: './Dashboard/Workplace',
      //       isMenuData: true,
      //     },
      //   ],
      // },



      {
        component: '404',
      },
    ],
  },
];
